import type {
  EngineeringCategoryId,
  EngineeringSymbolDefinition,
} from "./types";

export const DIAGRAM_PALETTE = {
  graphite: "#3f4243",
  modelBlue: "#b8d6eb",
  deepBlue: "#98b6cb",
  paleBlue: "#e4eff6",
  outlineBlue: "#78a9c8",
  warmGray: "#d9d8d6",
  paleGray: "#ececec",
  paper: "#ffffff",
  lavender: "#e9e5f3",
  sand: "#f3ead2",
  mint: "#e0eee9",
} as const;

export const ENGINEERING_CATEGORIES: ReadonlyArray<{
  id: EngineeringCategoryId;
  label: string;
  description: string;
}> = [
  {
    id: "flowchart",
    label: "Flowchart",
    description: "Processes, decisions, inputs, and terminals",
  },
  {
    id: "functional",
    label: "Functional",
    description: "Services, components, APIs, queues, and stores",
  },
  {
    id: "dfd",
    label: "Data flow",
    description: "Processes, entities, stores, and data movement",
  },
  {
    id: "uml",
    label: "UML",
    description: "Smart classes and structural elements",
  },
  {
    id: "ml",
    label: "ML / LLM architecture",
    description: "Book-style models, layers, tokens, tensors, and stages",
  },
];

export const ENGINEERING_SYMBOLS: readonly EngineeringSymbolDefinition[] = [
  {
    id: "flow-process",
    category: "flowchart",
    label: "Process",
    description: "A processing step",
    glyph: "▭",
    shape: "rectangle",
    backgroundColor: DIAGRAM_PALETTE.paleBlue,
  },
  {
    id: "flow-decision",
    category: "flowchart",
    label: "Decision",
    description: "A conditional branch",
    glyph: "◇",
    shape: "diamond",
    backgroundColor: DIAGRAM_PALETTE.sand,
  },
  {
    id: "flow-terminal",
    category: "flowchart",
    label: "Start / End",
    description: "Flow entry or termination",
    glyph: "◯",
    shape: "ellipse",
    backgroundColor: DIAGRAM_PALETTE.paleGray,
  },
  {
    id: "flow-io",
    category: "flowchart",
    label: "Input / Output",
    description: "Read or emit information",
    glyph: "I/O",
    shape: "diamond",
    backgroundColor: "#dceaf2",
  },
  {
    id: "flow-connector",
    category: "flowchart",
    label: "Connector",
    description: "Connect distant flow sections",
    glyph: "•",
    shape: "ellipse",
    backgroundColor: DIAGRAM_PALETTE.paper,
  },
  {
    id: "function-service",
    category: "functional",
    label: "Service",
    description: "Deployable service boundary",
    glyph: "SVC",
    shape: "rectangle",
    backgroundColor: DIAGRAM_PALETTE.modelBlue,
    rounded: true,
  },
  {
    id: "function-component",
    category: "functional",
    label: "Component",
    description: "Logical software component",
    glyph: "CMP",
    shape: "rectangle",
    backgroundColor: DIAGRAM_PALETTE.warmGray,
  },
  {
    id: "function-api",
    category: "functional",
    label: "API",
    description: "Synchronous interface or endpoint",
    glyph: "API",
    shape: "rectangle",
    backgroundColor: DIAGRAM_PALETTE.paleBlue,
    rounded: true,
  },
  {
    id: "function-queue",
    category: "functional",
    label: "Queue / Topic",
    description: "Asynchronous message channel",
    glyph: "MQ",
    shape: "rectangle",
    backgroundColor: DIAGRAM_PALETTE.sand,
    rounded: true,
  },
  {
    id: "function-database",
    category: "functional",
    label: "Database",
    description: "Persistent data store",
    glyph: "DB",
    shape: "ellipse",
    backgroundColor: DIAGRAM_PALETTE.mint,
  },
  {
    id: "dfd-entity",
    category: "dfd",
    label: "External Entity",
    description: "Source or destination outside the system",
    glyph: "EXT",
    shape: "rectangle",
    backgroundColor: DIAGRAM_PALETTE.lavender,
  },
  {
    id: "dfd-process",
    category: "dfd",
    label: "Process",
    description: "Transforms incoming data",
    glyph: "P",
    shape: "ellipse",
    backgroundColor: DIAGRAM_PALETTE.modelBlue,
  },
  {
    id: "dfd-store",
    category: "dfd",
    label: "Data Store",
    description: "Repository read or written by processes",
    glyph: "D",
    shape: "rectangle",
    backgroundColor: DIAGRAM_PALETTE.paleGray,
    rounded: true,
  },
  {
    id: "dfd-flow",
    category: "dfd",
    label: "Data Flow",
    description: "Named movement of data",
    glyph: "→",
    shape: "arrow",
    backgroundColor: "transparent",
  },
  {
    id: "uml-class",
    category: "uml",
    label: "Class",
    description: "Smart class with editable fields and methods",
    glyph: "C",
    shape: "rectangle",
    backgroundColor: "#dceaf2",
    smart: "class",
  },
  {
    id: "uml-interface",
    category: "uml",
    label: "Interface",
    description: "Smart interface contract",
    glyph: "I",
    shape: "rectangle",
    backgroundColor: "#dceaf2",
    smart: "class",
  },
  {
    id: "uml-package",
    category: "uml",
    label: "Package",
    description: "Namespace or module boundary",
    glyph: "PKG",
    shape: "rectangle",
    backgroundColor: DIAGRAM_PALETTE.sand,
    rounded: true,
  },
  {
    id: "ml-model",
    category: "ml",
    label: "Model block",
    description: "Primary model or architecture module",
    glyph: "MODEL",
    shape: "rectangle",
    backgroundColor: DIAGRAM_PALETTE.modelBlue,
    rounded: true,
  },
  {
    id: "ml-stage",
    category: "ml",
    label: "Stage container",
    description: "High-level training or processing stage",
    glyph: "STAGE",
    shape: "rectangle",
    backgroundColor: DIAGRAM_PALETTE.warmGray,
    rounded: true,
  },
  {
    id: "ml-layer",
    category: "ml",
    label: "Network layer",
    description: "LayerNorm, dropout, embedding, or output layer",
    glyph: "LAYER",
    shape: "rectangle",
    backgroundColor: DIAGRAM_PALETTE.paper,
    rounded: true,
  },
  {
    id: "ml-attention",
    category: "ml",
    label: "Attention block",
    description: "Self-attention or masked multi-head attention",
    glyph: "ATTN",
    shape: "rectangle",
    backgroundColor: "#626262",
    rounded: true,
  },
  {
    id: "ml-token",
    category: "ml",
    label: "Token / Input",
    description: "Tokenized text, input, or output value",
    glyph: "TOKEN",
    shape: "rectangle",
    backgroundColor: DIAGRAM_PALETTE.paper,
    rounded: true,
  },
  {
    id: "ml-tensor",
    category: "ml",
    label: "Tensor / Matrix",
    description: "Embedding, weight, or attention matrix",
    glyph: "[ ]",
    shape: "rectangle",
    backgroundColor: DIAGRAM_PALETTE.paleBlue,
  },
  {
    id: "ml-pipeline-group",
    category: "ml",
    label: "Pipeline group",
    description: "Outlined grouping boundary for a processing pipeline",
    glyph: "GROUP",
    shape: "rectangle",
    backgroundColor: "transparent",
    rounded: true,
  },
];

export const getSymbolDefinition = (definitionId: string) =>
  ENGINEERING_SYMBOLS.find((definition) => definition.id === definitionId);
